### ISSUE TITLE
Mi 10 ultra: enable N5/N8 problem

### ISSUE THREAD

**Issue by andrea-musci** [Weverses/ModemPro#5]
Hi, I'm on Mi 10 ultra with MIUI 13.0.5 xiaomi.eu. If I dial `*#*#65686633#*#*` nothing happens: there's no message or menu that opens up.
What is supposed to happen? How can I tell if N5/N8 is enabled?
Thanks

**Comment by Weverses** [comment]
The reason why there's no toast message in it is that MIUI v13.0.5 didn't support N5/N8 in TeleSevice.apk, I recommend that you should update your device to the latest DEV version.

**Comment by andrea-musci** [comment]
Ok thank you. I'll wait for next stable release and see.

**Comment by andrea-musci** [comment]
@Weverses are you on Mi 10 Ultra? Can you send me your TeleService.apk? Thx
